### ISSUE TITLE
Why should one use jsUri over URI.js?

### ISSUE THREAD

**Issue by JamesCropcho** [derek-watson/jsUri#49]
I very much hope you don't see the question as trolling- it's an honest question.

I see that URI.js has many more Github stars, and have trouble seeing the differences between you two.

I'm sure each has pros and cons, but they aren't listed in the README- any thoughts?

Thanks,
James

**Comment by derek-watson** [comment]
I wrote this back in 2010 to scratch an itch and to be honest I haven't used either this library or Uri.js since then. Other people continue to use and maintain jsUri by contributing features and tests, so here we are.

If you'd like to compare them both I'd be happy to accept a pull request with a comparison matrix in the README.md. 

Thanks!

**Comment by derek-watson** [comment]
Also, I could be wrong but I think people might choose this one if they want to manipulate the details of the url query params? Just a guess!

**Comment by JamesCropcho** [comment]
Hi Derek,

Thanks- I appreciate the honest answer. Well, you should be proud of starting a self-sustaining open source project. I went with URI.js to build what I needed on Thursday but if I feel the slightest friction or jankiness with it then I'll look to jsUri immediately.

-James

**Comment by user453584** [comment]
I also appreciate the honest answer, as I had not heard of URI.js and it turned out to be a better fit for my needs.
